/* Quiz do Tema 06. Perguntas e explicações baseadas no texto da apostila (páginas 76 a 84 do PDF).
   A alternativa correta é sempre a primeira da lista; o painel embaralha a ordem ao iniciar. */
criarPainel({
  rootId: 'dynamicContent',
  liveId: 'quizLive',
  storageKey: 'ux_tema06_quiz_v1',
  itemLabel: 'Questão',
  nextLabel: 'Avançar',
  lastLabel: 'Ver resultado',
  restartLabel: 'Tentar novamente',
  shuffle: true,
  items: [
    { text: "Qual é o objetivo principal da experiência do usuário (UX)?",
      options: ["Melhorar a satisfação do cliente, deixando a interação com o produto o mais simples e eficiente possível",
                "Aumentar a quantidade de produtos vendidos, sem considerar a opinião do usuário",
                "Reduzir ao mínimo o custo de desenvolvimento do produto",
                "Substituir o atendimento humano por atendimento online"],
      correct: 0,
      hint: "Pense no que o resumo do capítulo diz sobre satisfação e simplicidade.",
      explanation: "O capítulo resume que o objetivo principal da UX é melhorar a satisfação do cliente, deixando a interação do usuário com o produto o mais simples e eficiente possível." },

    { text: "O que é um feedback e por que ele é importante para a UX?",
      options: ["É a informação dos usuários sobre como interagem com o produto, e mostra áreas de melhoria e inovação",
                "É o relatório financeiro que mostra o lucro do produto em cada mês",
                "É a nota que a empresa dá ao trabalho da equipe de design",
                "É a lista das funcionalidades que o produto ainda vai receber"],
      correct: 0,
      hint: "O capítulo diz que o feedback dos usuários aponta o que melhorar.",
      explanation: "O feedback dos usuários mostra como eles interagem com o produto e permite identificar áreas para melhoria e inovação." },

    { text: "Qual analogia a apostila usa para explicar a lógica do usuário no mundo digital?",
      options: ["A trilha aberta em uma praça por pessoas que preferem o atalho à calçada",
                "Um rio que sempre segue o caminho mais longo até o mar",
                "Uma biblioteca com os livros organizados por cor",
                "Um semáforo que controla o fluxo de carros em uma avenida"],
      correct: 0,
      hint: "A imagem tem uma praça, uma calçada e um percurso mais curto.",
      explanation: "Mesmo com a calçada em ótimas condições e sinalizada, as pessoas preferem a trilha porque ela corta o percurso e gasta menos tempo. O usuário digital também busca economizar tempo a partir de uma experiência positiva." },

    { text: "O que mudou quando o design entrou na concepção dos modelos de negócio?",
      options: ["O usuário passou ao centro de todo o processo de criação, validação e monitoramento",
                "A equipe de vendas passou ao centro de todo o processo de criação",
                "A etapa de validação com os usuários deixou de existir",
                "As empresas passaram a medir apenas a quantidade de produtos vendidos"],
      correct: 0,
      hint: "A resposta fala de quem fica no centro do processo.",
      explanation: "O que as pessoas buscam, como reagem e o sentimento que carregam viraram o ponto de partida dos negócios. Antes, as empresas tentavam adivinhar ou convencer as pessoas de algo que nem sempre agregava valor real." },

    { text: "Quem criou o framework HEART?",
      options: ["O Google Ventures, em parceria com a Digital Telepathy",
                "O Hotjar, em parceria com o Google Analytics",
                "A Apple, em parceria com a Microsoft",
                "O YouTube, em parceria com a Netflix"],
      correct: 0,
      hint: "O nome de uma das criadoras começa com Google.",
      explanation: "A apostila informa que o HEART foi criado pelo Google Ventures em parceria com a Digital Telepathy, para ajudar a escolher as métricas que melhoram a experiência do usuário." },

    { text: "Na categoria Happiness, o NPS ajuda a definir se cada cliente é:",
      options: ["Promotor ou detrator do produto",
                "Novo ou antigo no produto",
                "Ativo ou cancelado na plataforma",
                "Rápido ou lento para concluir uma tarefa"],
      correct: 0,
      hint: "O NPS separa os clientes pela opinião que têm do produto.",
      explanation: "Primeiro se define se o cliente é promotor ou detrator. Depois esses dados são cruzados com outras pesquisas qualitativas para ter uma ideia geral do nível de felicidade dos usuários." },

    { text: "Quais ferramentas a apostila cita para medir o engajamento?",
      options: ["Google Analytics e Hotjar",
                "NPS e churn rate",
                "Airbnb e iFood",
                "Taxa de rejeição e taxa de conversão"],
      correct: 0,
      hint: "Uma delas é descrita como completa e gratuita.",
      explanation: "Para medir o engajamento, a apostila cita o Google Analytics, uma ferramenta completa e gratuita, e o Hotjar, entre outras que analisam as atividades dos usuários dentro do aplicativo ou da plataforma." },

    { text: "O que a categoria Adoption mede?",
      options: ["A quantidade de novos usuários do produto em um período de tempo",
                "A quantidade de usuários que permanecem ativos ao longo do tempo",
                "O nível de satisfação do usuário medido em pesquisas",
                "O quanto é fácil concluir a tarefa essencial do produto"],
      correct: 0,
      hint: "Pense em novos usuários e em novas funcionalidades.",
      explanation: "A adoção mede a quantidade de novos usuários em um período de tempo e também os usuários novos de uma funcionalidade recém-criada." },

    { text: "A retenção está ligada a qual indicador?",
      options: ["Churn rate, a taxa de cancelamento",
                "Taxa de conversão, que mede o objetivo atingido",
                "Taxa de rejeição, que mede as sessões de uma página",
                "Número de upgrades para a versão mais recente"],
      correct: 0,
      hint: "O indicador acompanha os usuários que cancelam.",
      explanation: "A retenção está ligada ao churn rate. Como o custo de adquirir novos usuários pode ser alto, uma taxa de churn alta é um indício preocupante para o produto." },

    { text: "Em um e-commerce, qual é a tarefa essencial analisada em Task Success?",
      options: ["A compra do produto",
                "A criação de um perfil de usuário",
                "A leitura da política de privacidade",
                "O envio de uma avaliação depois da compra"],
      correct: 0,
      hint: "É a tarefa para a qual o e-commerce existe.",
      explanation: "A apostila dá esse exemplo: no e-commerce, a tarefa essencial é a compra do produto. Se o caminho até ela for muito complicado ou difícil, há uma falha grave de usabilidade." },

    { text: "Qual é a ordem das etapas para usar o framework HEART?",
      options: ["Metas, sinais e métricas",
                "Métricas, metas e sinais",
                "Sinais, métricas e metas",
                "Métricas, sinais e metas"],
      correct: 0,
      hint: "Primeiro se decide o que se quer alcançar.",
      explanation: "Primeiro se definem as metas, depois se mapeiam os sinais e, por fim, se escolhem as métricas mais importantes e viáveis para o produto." },

    { text: "Por que é preciso selecionar as métricas e estabelecer KPIs?",
      options: ["Porque o que não pode ser medido não pode ser melhorado",
                "Porque todo negócio deve usar exatamente os mesmos KPIs",
                "Porque os KPIs substituem a escuta dos usuários",
                "Porque as métricas dispensam a definição de metas"],
      correct: 0,
      hint: "Uma máxima do mundo dos negócios responde a esta pergunta.",
      explanation: "A máxima diz que o que não pode ser medido não pode ser melhorado. A escolha das métricas depende do tipo de negócio, dos objetivos e dos problemas que se quer resolver." },

    { text: "O que é a relação entre atendimento online e offline?",
      options: ["A relação entre os clientes atendidos offline e o número de visitantes do site",
                "O total de vendas feitas em lojas físicas em cada mês",
                "O tempo médio de resposta do chat do site",
                "A quantidade de páginas visitadas em cada sessão"],
      correct: 0,
      hint: "Em um e-commerce com autoatendimento, esse número precisa ser baixo.",
      explanation: "Em um e-commerce com modelo de autoatendimento, o número de clientes que recorrem ao atendimento offline precisa ser baixo. Por isso se acompanha a relação entre os clientes atendidos offline e os visitantes do site." },

    { text: "O que a taxa de rejeição mede e o que uma taxa alta pode sugerir?",
      options: ["Mede as sessões com uma única página visitada, e uma taxa alta pode sugerir dificuldade de navegação ou problema técnico",
                "Mede quantos usuários concluíram a compra, e uma taxa alta indica que o produto vende bem",
                "Mede quantos usuários cancelaram a assinatura, e uma taxa alta indica boa retenção",
                "Mede o tempo gasto no site, e uma taxa alta indica que o usuário gostou do produto"],
      correct: 0,
      hint: "Visitar uma única página nem sempre é ruim.",
      explanation: "A taxa de rejeição mede as sessões em que só uma página foi visitada. Isso nem sempre é negativo, porque o usuário pode ter achado a informação que buscava, mas uma taxa alta pode sugerir dificuldade de navegação ou algum problema técnico." },

    { text: "O que é a taxa de conversão e quais objetivos ela pode ter?",
      options: ["É uma métrica do marketing como um todo, e o objetivo pode ser comprar, preencher um questionário, pedir um orçamento ou acessar uma área estratégica do site",
                "É uma métrica exclusiva de UX, e o único objetivo possível é a compra",
                "É o número de novos usuários por mês, e o objetivo é sempre crescer",
                "É a taxa de cancelamento dos usuários, e o objetivo é sempre reduzi-la"],
      correct: 0,
      hint: "A apostila diz que o que importa é atingir o objetivo proposto.",
      explanation: "A taxa de conversão vem do marketing como um todo e não é estritamente de UX. O que importa é que o objetivo proposto seja atingido: uma compra, um questionário preenchido, um orçamento pedido ou o acesso a uma área estratégica do site." }
  ],
  renderResult: function (r) {
    var msg = "Releia a página Conteúdo e tente de novo.";
    if (r.percent === 100) msg = "Você acertou todas as questões.";
    else if (r.percent >= 80) msg = "Você acertou a maior parte. Revise as questões que errou na página Conteúdo.";
    else if (r.percent >= 60) msg = "Você acertou mais da metade. Releia as seções sobre o HEART e os KPIs.";
    return '<h2 id="painelResultado" tabindex="-1">Resultado</h2>' +
      '<div class="final-score-text">' + r.correct + ' / ' + r.total + '</div>' +
      '<p>' + msg + '</p>';
  }
});
